apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  userInitPassword: userInitPass
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
type: Opaque
data:
  username: admin
  password: admin